# Generated by Django 5.1.6 on 2025-02-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='financial_goals',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_role',
        ),
    ]
