# Generated by Django 5.1.6 on 2025-04-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_messaging_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='specialties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
