services:
  db:
    container_name: wealthwise-db
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wealthwise_db
      POSTGRES_USER: wealthwise_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: on-failure

  web:
    build: .
    container_name: wealthwise-web
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: wealthwise_db
      DATABASE_USER: wealthwise_user
      DATABASE_PASSWORD: securepassword
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    volumes:
      - .:/app

volumes:
  db-data: