services:
  - type: web
    name: wealthwise
    env: docker
    plan: free
    buildCommand: docker build -t wealthwise .
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: wealthwise-db
          property: connectionString

databases:
  - name: wealthwise-db
    plan: free
    databaseName: wealthwise
    user: wealthwise
