# Generated by Django 5.1.6 on 2025-03-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_end_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_start_time",
        ),
        migrations.AddField(
            model_name="event",
            name="event_end_timestamp",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="event_start_timestamp",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
