# Generated by Django 5.1.6 on 2025-03-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_remove_event_event_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organizer_id",
        ),
    ]
