# Generated by Django 5.1.6 on 2025-03-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_remove_event_organizer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_type",
        ),
    ]
