# Generated by Django 5.1.6 on 2025-04-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_eventregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventregistration",
            name="id",
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="registration_id",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
