# Generated by Django 5.1.6 on 2025-04-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_remove_eventregistration_id_and_more"),
        ("users", "0005_remove_advisor_advisor_id_remove_advisor_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_slots", models.JSONField(blank=True, default=list, null=True)),
                (
                    "blockedDateTime",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.advisor"
                    ),
                ),
            ],
        ),
    ]
