# Generated by Django 5.1.6 on 2025-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_advisoravailability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoravailability",
            name="time_slots",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
