# Generated by Django 5.1.6 on 2025-04-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0009_remove_advisoravailability_time_slots_timeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.timeslot",
            ),
        ),
    ]
