# Generated by Django 5.1.6 on 2025-04-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_consultation_time_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Cancelled By User", "Cancelled By User"),
                    ("Cancelled By Advisor", "Cancelled By Advisor"),
                    ("Cancelled By Admin", "Cancelled By Admin"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
