# Generated by Django 5.1.6 on 2025-02-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialToolUsage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_type', models.CharField(max_length=20)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('usage_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
