# Generated by Django 5.1.6 on 2025-02-27 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtoolusage',
            name='budget_for_date',
            field=models.DateField(default=datetime.date(1000, 10, 10)),
        ),
    ]
